Repository wptide/wptide.org, pull requests merged in 2021-03, with the labels that each got.

#42 Add a Status component to expose the state of an Audit
  .eslintrc.json
  app/src/run/auditServer.js
  app/src/util/auditHelpers.js
  app/src/util/canProceed.js
  app/tests/unit/controllers/getAudit.test.js
  firestore.rules
  package-lock.json
  package.json
  web/.vuepress/components/Hero.vue
  web/.vuepress/components/LogoGrid.vue
  web/.vuepress/components/SpecFrame.vue
  web/.vuepress/components/StatusList.vue
  web/.vuepress/components/status/Pagination.vue
  web/.vuepress/components/status/Project.vue
  web/.vuepress/components/status/Report.vue
  web/.vuepress/components/status/Select.vue
  web/.vuepress/components/status/Status.vue
  web/.vuepress/config.js
  web/.vuepress/public/assets/img/icon-status-complete.svg
  web/.vuepress/public/assets/img/icon-status-failed.svg
  web/.vuepress/public/assets/img/icon-status-in-progress.svg
  web/.vuepress/public/assets/img/icon-status-pending.svg
  web/.vuepress/public/assets/img/icon-status-unknown.svg
  web/.vuepress/public/assets/script-loader.js
  web/.vuepress/util/processTime.js
  web/docs/status/README.md
Labels: enhancement

#44 Fix typos & update directions for setting the Firebase project ID
  app/tests/unit/util/shouldLighthouseAudit.test.js
  web/docs/installation/README.md
Labels: documentation

#45 Update app-server NPM dependencies
  app/package-lock.json
  app/package.json
Labels: dependency

#46 Refactor the Status schema & add sorting to the Vue component
  app/openapi.yml
  app/src/run/auditServer.js
  app/src/util/auditHelpers.js
  app/src/util/canProceed.js
  app/src/util/setAuditStatus.js
  app/tests/unit/controllers/getAudit.test.js
  app/tests/unit/util/setAuditStatus.test.js
  web/.vuepress/components/StatusList.vue
  web/.vuepress/components/status/Project.vue
  web/.vuepress/components/status/Report.vue
  web/.vuepress/components/status/Select.vue
  web/.vuepress/config.js
  web/.vuepress/public/assets/app.js
  web/docs/README.md
  web/docs/status/README.md
Labels: enhancement

#47 Prepare the sync ingest for a database rebuild
  Makefile
  app/src/util/doSync.js
  firebase.json
  firestore.indexes.json
  web/.vuepress/public/assets/app.js
Labels: enhancement

#48 Refactors the status logic & fixes UI bugs
  .env.dist
  .env.server.dist
  Makefile
  app/openapi.yml
  app/src/audits/lighthouseReporter.js
  app/src/audits/phpcsReporter.js
  app/src/controllers/getAudit.js
  app/src/integrations/firestore.js
  app/src/run/auditServer.js
  app/src/services/firestore.js
  app/src/util/auditHelpers.js
  app/src/util/canProceed.js
  app/src/util/phpcsHelpers.js
  app/tests/unit/audits/lighthouseReporter.test.js
  app/tests/unit/audits/phpcsReporter.test.js
  app/tests/unit/controllers/getAudit.test.js
  app/tests/unit/integrations/firestore.test.js
  app/tests/unit/run/auditServer.test.js
  app/tests/unit/util/canProceed.test.js
  app/tests/unit/util/doSync.test.js
  web/.vuepress/components/status/Project.vue
  web/.vuepress/components/status/Report.vue
Labels: bug

#49 Ensure coverage is 100%
  app/src/util/phpcsHelpers.js
  app/src/util/phpcsRunner.js
  app/tests/unit/util/canProceed.test.js
  app/tests/unit/util/phpcsHelper.mock.test.js
Labels: test
